services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile  # Dockerfile original para desarrollo
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: python run.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Dockerfile original para desarrollo
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

networks:
  default:
    driver: bridge